INSERT INTO `words` VALUES (1,'mood','настрій',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (2,'window','вікно',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (3,'door','двері',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (4,'wall','стіна',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (5,'affair','справа',NULL,'подія, інцидент, міроприємство, явище',2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (6,'distinguish','розрізняти',NULL,'відрізняти, роздивлятися, розглядати, виділяти, характеризувати',1,'regular',NULL,NULL);
INSERT INTO `words` VALUES (7,'towel','рушник',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (8,'engage','зацікавлювати',NULL,NULL,1,'regular',NULL,NULL);
INSERT INTO `words` VALUES (9,'assume','передбачати',NULL,NULL,1,'regular',NULL,NULL);
INSERT INTO `words` VALUES (10,'sneak','крастися',NULL,'підкрадатися',1,'irregular','sneacked, snuck','sneacked, snuck');
INSERT INTO `words` VALUES (11,'scramble','сутичка',NULL,NULL,2,NULL,NULL,NULL);
INSERT INTO `words` VALUES (12,'sing','співати',NULL,NULL,1,'irregular','sang','sung');
INSERT INTO `words` VALUES (13,'lend','позичати',NULL,NULL,1,'irregular','lent','lent');
INSERT INTO `words` VALUES (14,'essential','невідємливий',NULL,'необхідний, важливий, суттєвий',3,NULL,NULL,NULL);
